### ISSUE TITLE
Audio file sent by extrange number everytime I open Loqui

### ISSUE THREAD

**Issue by 03927e9c** [loqui/im#1001]
Since I installed the latest version as for today, I keep getting an audio file every time I open Loqui. I do not know who it is, but it doesn't have a regular number composition. It has 10 digits (xxxxxxxxxx@broadcast) That's the sender info, no avatar of course. I won't put the number until I know what the hell is it. I haven't clicked on the audio file neither.
![pantallazo](https://cloud.githubusercontent.com/assets/9679446/14160580/870db8c6-f6b3-11e5-8ee0-69db9369f15d.png)

I tried muting and hiding the chat but it won't work. Help please, thanks.

**Comment by TitanNano** [comment]
I'm just guessing,  but I think this a broadcast someone sent to you. As far as I know loqui doesn't know how to handle those. You don't know that phone number? loqui/im schrieb:Since I installed the latest version as for today, I keep getting an audio file every time I open Loqui. I do not know who it is, but it doesn't have a regular number composition. It has 10 digits (xxxxxxxxxx@broadcast) That's the sender info, no avatar of course. I won't put the number until I know what the hell is it. I haven't clicked on the audio file neither.

I tried muting and hiding the chat but it won't work. Help please, thanks.

**Comment by cmeerw** [comment]
As always, some logs would be useful...

**Comment by cmeerw** [comment]
Handling of broadcast messages has been improved in 0.5.3 and again in current github sources, closing.
