### ISSUE TITLE
Chat always jumps down to the newest message, when a new message is sent

### ISSUE THREAD

**Issue by tibtab** [loqui/im#1026]
I think this is kind of annoying, i.e when you are reading messages sent in a group, because you weren't online for two days and there are hundreds of new messages in a new group and each time there is somebody who sends a new message you have to scroll up to the point where you were with reading, and when you read about two words and the chat jumps down again...

**Comment by Honk2** [comment]
There are 4 events that trigger the scrolling a the chat
- text input get focus
- text input lost focus
- new message arrives
- new message is send/displayed

I agree to remove the first two, because this will make the chat jump, if you start typing or change to and from emojis. And if you answer to the latest messages, the chat is probaply scrolled down anyway.

If we remove number 3, there should be an indicator in the header. 

@titab and anyone else, what is your opinion on number 4, scrolling after sending?

**Comment by tibtab** [comment]
I think it is good, that the chat scrolls down when you send a new message, it is good to see if your message is send, because it happens still to often, that messeges are not sent (i.e. because of a bad connection or something)

for number 3 maybe it is possible, that there appears for about 3 seconds a little sign in the bottom of the screen which you can tap to automatically scroll down

**Comment by Honk2** [comment]
ok, I am working on that.
