### ISSUE TITLE
[xmpp] Can't connect to xmpp account any more

### ISSUE THREAD

**Issue by tibtab** [loqui/im#1061]
Tries to connect with bosh.loqui.im but ther happens nothing else, the beam stays yellow

**Comment by cmeerw** [comment]
Yes, bosh.loqui.im is no more - and it's unlikely to come back.

**Comment by tibtab** [comment]
so there won't be any xmpp support any more?

**Comment by cmeerw** [comment]
There is still XMPP support, but you need to either connect directly
to the XMPP server (which unfortunately doesn't work for all XMPP
servers due to limitations in the TCPSocket API) or use a
BOSH/WebSocket server offered by the XMPP server operator (or use some
other BOSH/WebSocket server to connect - but I am not aware of any
completely open one to the public).

As bosh.loqui.im was a man-in-the-middle, it never was a very good
solution anyway (although it was convenient for users).

**Comment by tibtab** [comment]
How can I connect directly to the server?

**Comment by cmeerw** [comment]
On the Jabber set up screen you can specify the host to connect to.
For direct TCP connections use "tcp:example.com:5222" if the XMPP
server is example.com. Loqui tries to suggest a host based on the XMPP
server's DNS records.

**Comment by tibtab** [comment]
Ok thanks
