### ISSUE TITLE
Unsynchronized conversations

### ISSUE THREAD

**Issue by ZxCraft** [loqui/im#1228]
Had the version 0.5.11 of loqui im ​​for firefox os, update to the last version (0.5.17) by the webIDE. But now I have two loqui im, and in the new version are not the previous conversations, does anyone know how I can synchronize the conversations? I am using the same number in both accounts and nothing....
Also in the incoming messages (of groups and of conversations) appears DECRYPT ERROR .....
It will be a bug of the version or by my cell phone, my cell phone is a ZTE Open II
Please. help.
Thanks

**Comment by Honk2** [comment]
It seems you do not have updated the old install, but installed a second instance. This happens when you install from a different source location than the previous install.
The second install gets a new app id.

You will need to export from 0.5.11 (webide > console > App.exportData() ) and import into 0.5.17 App.inportData()

**Comment by Honk2** [comment]
See issue #1182

**Comment by Honk2** [comment]
Tge decrypt errors will vanish after some time when the new keys because of the new install have been generated and shared.

**Comment by nfsprodriver** [comment]
Duplicate, sorry...
