### ISSUE TITLE
It doesn't show more than two messages per intervention.

### ISSUE THREAD

**Issue by juaneladio** [loqui/im#127]
I noticed that in [Whatsapp] when somebody write more than 2 'messages', when I reconnect I see all the messages as notifications, but when I open the specific chat I only see the first one and the last one. All other messages doesn't appear. I attach screenshots.

**Comment by juaneladio** [comment]
These are the notifications: I have 4+1 messages from a contact.
1. Estas como activo
..
4. Twitter.

![2013-12-01-09-14-03](https://f.cloud.github.com/assets/547722/1651724/aa23efcc-5aea-11e3-8168-cd42096d2558.png)

**Comment by juaneladio** [comment]
This is the chat. I only see the first message "1. Estas como activo" and the last one "4. Twitter".

![2013-12-01-09-14-16](https://f.cloud.github.com/assets/547722/1651726/c09ce0a6-5aea-11e3-927b-304bfd749943.png)

**Comment by juaneladio** [comment]
I just remembered that I had the same issue with a Google Hangout chat. I leaved the app for a while, then I received three messages from a contact in the notifications area. When I open the conversation I only see the first and the last one.

![2013-11-30-21-34-54](https://f.cloud.github.com/assets/547722/1651793/f2787bf4-5aee-11e3-94b5-d015075a7f59.png)

**Comment by aarizkuren** [comment]
I have the same issue too

**Comment by aesedepece** [comment]
I have a theory on what may be causing this awful issue. I'l make some test and keep you updated.

**Comment by aesedepece** [comment]
Hi guys, this is what happened:

When you received a lot of messages in a short period of time, each one was being written to memory without waiting for the previous one to be successfully stored. This caused all the previous messages to vanish!

The solution was to push every message to a asynchronous queue so that they can be processed in order and they don't overwrite each other.
