### ISSUE TITLE
Contacts are showed always as "Disconnected"

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#20]
Hi,

Today I installed loqui and log in with my GTalk and when I watched my contacts list all was showed as Disconnected. 15 minutes later one of 57 contacts listed was showed as Available. Is this a Bug? Something wrong?

Tested in a Unagi phone with FirefoxOS and a Samsung Galaxy S3 with Firefox for Android.

Regards,

**Comment by aesedepece** [comment]
We are aware of it. Google servers do not send contacts' presence on log in.

It's not secret that Google Talk implements some features by using their own XMPP extensions instead of that proposed for community approval in XEP documents.

We are trying to figure out all of those little differences between standard XMPP and Google's XMPP in order to support them on an equal basis.

**Comment by Gioyik** [comment]
So bad, probably in the future this will be fixed with help of XEP, I am going to read something about it to know how to help to fix this, it's not sure that I find out the solution. :P
