### ISSUE TITLE
Can't login on whatsapp

### ISSUE THREAD

**Issue by rafaelmr2** [loqui/im#262]
Hi,

When I try to login on whatsapp it shows 2 steps: "waiting for SMS" and "Sincronizando" quickly. And don't receive the SMS and show "0 contacts imported". I'm using Firefox OS 1.3 on Peak and the latest version from Loqui 2.5 (from github). I use the debug function from Firefox, follow:

XXX

**Comment by aesedepece** [comment]
These are my conclussions from reading the logs:
- You have previously set up WhatsApp, so you don't need to receive another verification code over SMS because the your account's device ID matches the one stored in /sdcard/.coseme.id
- The login and auth processes are succesful
- Your contacts are not being imported because the https://github.com/andreasgal/PhoneNumber.js  fails to verify them as valid Brasil cellular phone numbers. You can check it fails with this test: http://logofid.es/phonenumberjs_test/

Consequences:
- We could switch to https://code.google.com/p/libphonenumber/ which seems to properly verify your numbers: http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html

WARNING: Be careful, man. Those logs expose your phone number and device ID to anyone out there in the wild net. We recommend you to delete or edit them, because if malicious people get your device ID they could be able to compromise your WhatsApp account.

**Comment by rafaelmr2** [comment]
Thanks for help! 

My numbers are valid, I made the test.

**Comment by aesedepece** [comment]
What's the current status of this issue? Have you experienced this in 0.3.0d? Thanks!

**Comment by rafaelmr2** [comment]
I can login in new version :) Thanks
