### ISSUE TITLE
Remove or change the re-authentication of Whatsapp account message

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#298]
0.2.5c on GP Peak, B2G 1.1.1.0hd-GP (stable).

From time to time, the re-authentication of Whatsapp account message (The authentication of your account is no longer valid. Please, re enter your phone number to receive back a code (SMS) confirmation and a valid authentication to your account) appears.
There is no way to actually re-enter the phone number, no matter of clicking or not clicking this message.

BTW, is this message related to the fact of not purchasing Whatsapp licence?

**Comment by aesedepece** [comment]
The "authentication of your account is no longer valid" made sense some releases ago, but it isn't accurate any more. It means instead that the authentication failed for an unknown reason.

**Comment by bdcomp** [comment]
Still not clear, as a few seconds after this message everything works just fine...

@aesedepece Should I open a new issue about wrong message?

**Comment by aesedepece** [comment]
@bdcomp Just rename this.

Further explanation: the error notification was binded to the `authfail` event a few releases ago, when we had no method to reconnecting after such socket errors. Nowadays, the app reconnects automatically after disconnections or socket errors, so no error notifications should be shown at all.

Anyway, I'm currently working on optimizing the connections so that the socket never die and we don't have to face these situations.
