### ISSUE TITLE
Connect to Gtalk with custom domain name

### ISSUE THREAD

**Issue by borislas** [loqui/im#32]
Hello,

I can't connect to Google Talk with a custom domain name.

I guess Loqui only uses the Google server if the IADB ends with "gmail.com".

Is it possible to have the opportunity to choose the type of account?
For example Jabber with the possibility to enter the server address or GTalk which predetermines the server address.

Thanks!

**Comment by aesedepece** [comment]
Somebody told us about this issue some days ago via mail.

Contrary to what you may think, LOQUI does not make any distinctions between Google Talk or Jabber. It just takes your JID and split it in username and domain. Then it tries to log into that domain using your username and password.

The problem with Google Apps accounts is that server name differs from the user's domain, so LOQUI tries to connect to `yourdomain.com:5222` instead of `talk.google.com:5222`, where your chat server really is.

**Comment by aesedepece** [comment]
The guy who told us about this issue first has managed to solve it.

In order to use Google Apps accounts in LOQUI and other clients that makes no distinction from domain and server, you have to modify your domain's DNS records as described in this Google Apps help page:
http://support.google.com/a/bin/answer.py?hl=en&hlrm=es&answer=34143

Please apply those changes (or encourage the sysadmin to do so) and tell us if that works for you. Notice that changes to DNS records may take up to 48h to take effect.

**Comment by axllent** [comment]
Hi @aesedepece. I made the necessary DNS changes described on the Google support site, however I still cannot connect to my Google Apps domain (it's been two weeks since I made the changes). You mentioned port 5222, however the DNS entries are for port 5269 - could this be the reason?

If I `dig _xmpp-server._tcp.gmail.com srv` or use my own domain name, they say the same thing, so I'm pretty sure it's not the DNS...

**Comment by temowani** [comment]
Hi @aesedepece. You are wrong or you do not have tried to implement the solution that you was posted.

Hey @axllent
The correct solution for that problem is add or replace your DNS Records like shown below

```
          _xmpp-server._tcp.domain.com. IN SRV 5 0 5269 xmpp-server.l.google.com.
          _xmpp-server._tcp.domain.com. IN SRV 20 0 5269 alt1.xmpp-server.l.google.com.
          _xmpp-server._tcp.domain.com. IN SRV 20 0 5269 alt2.xmpp-server.l.google.com.
          _xmpp-server._tcp.domain.com. IN SRV 20 0 5269 alt3.xmpp-server.l.google.com.
          _xmpp-server._tcp.domain.com. IN SRV 20 0 5269 alt4.xmpp-server.l.google.com.

          _xmpp-client._tcp.domain.com. IN SRV 5 0 5222 xmpp.l.google.com.
          _xmpp-client._tcp.domain.com. IN SRV 20 0 5222 alt1.xmpp.l.google.com.
          _xmpp-client._tcp.domain.com. IN SRV 20 0 5222 alt2.xmpp.l.google.com.
          _xmpp-client._tcp.domain.com. IN SRV 20 0 5222 alt3.xmpp.l.google.com.
          _xmpp-client._tcp.domain.com. IN SRV 20 0 5222 alt4.xmpp.l.google.com.
```
