### ISSUE TITLE
Comments in en.ini appears as [empty string]

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#349]
As I was last editing en.ini, it's maybe because of me, but comments (like "# WELCOME SCREEN") in en.ini appears as [empty string] for translation, while earlier were not visible at all.

@aesedepece Any thoughts what was garbled?

**Comment by aesedepece** [comment]
The comments are not supposed to be translated, they are references that need to be present only in 'en.ini' because it's the only localization file that is edited manually and we need those references to quickly find a string if we need to modify it.

I've marked those lines as hidden to the translation system.

**Comment by bdcomp** [comment]
@aesedepece I am familiar with code comments :)

These lines still visible as [empty string]...
