### ISSUE TITLE
[XMPP] Can neither receive nor send msgs

### ISSUE THREAD

**Issue by ghost** [loqui/im#379]
hello all,

when tapping on the "Speech balloon" icon nothing happens. And tapping on "enter" creates a new line. So there is no possibility to send msgs.

On the other hand when receiving msgs, only the internet activity symbol in the upper bar reacts. the msgs are not shown in loqui.

Can you please check this behaviour?

Using ffxos 1.1 on Peak

Thank you very much.

**Comment by aesedepece** [comment]
Thanks for reporting.

This issue happens because we sadly didn't take into account that FFOS 1.1 uses Gecko 18, which lacks of support for ECMA 6 and JS 1.7 functions such as `Array.prototype.find()` which we've been using extensively.

We are now moving back to `Lungo.Core.findByProperty` so that we keep backwards compatibility while there are still 1.1 phones out there.
