### ISSUE TITLE
GMail dropping XMPP, what will you do?

### ISSUE THREAD

**Issue by ntrrgc** [loqui/im#40]
"GMail compatible" is one of the promises of Loqui, but the new Google Hangouts breaks that with incompatible and closed technology.

**Comment by markuman** [comment]
someone has to reverse engineer the protocol, otherwise gmail will be dropped i guess.

**Comment by aesedepece** [comment]
Like you said, the Hangouts app makes no longer use of XMPP but a closed protocol instead. Nevertheless, you can still access your account via XMPP and their servers keep federating.

We can't understand why is Google moving in this dumb direction, given that XMPP is a growing standard that is being used even by Microsoft Lync, Facebook and Tuenti (though these last two don't federate).

The fact is that Google has still not made a formal statement on their plans to keep that backward compatibility or whether to drop XMPP and all the cool interoperating thing.

If they eventually drop XMPP, we'll encourage everyone to move to any other provider. There are many other reasons to do so: more extensions support, cyphered communications, no PRISM back-doors...

Reverse engineering Hangouts is not a short term plan for us, but if it gets eventually scrapped we'll considerate supporting it, sure.

My personal stance is that for XMPP there's life after Google. They have just gotten off a boat that is about to weigh anchor for the awesomeness ;)

**Comment by markuman** [comment]
nsa prism
these two words were just missing in this discussion

**Comment by aesedepece** [comment]
Lately those words seem to be even in every table talk...

Seriously, secrecy of communications and personal data protection are nowadays issue of concern just because they have to.

We all should pay a little more attention to how our data is being stored and handled by the companies running the services we love, and to how they share it with third parties for unknown purposes even without our consent.

Apart from that and going back to the point, we the users should make Google understand that dropping XMPP is not a good idea and thousands of us will be really upset if they don't back down from their stupid position.

Indeed, the Hangouts Android app reception has been hated and rejected by lots of users and it's receiving rather bad reviews according to its Google Play rating:
https://play.google.com/store/apps/details?id=com.google.android.talk
