### ISSUE TITLE
Make the app less phone-centric

### ISSUE THREAD

**Issue by airon90** [loqui/im#439]
Loqui must be device independent: e.g. there are some strings saying that the app is running on a phone. [Some tablets](https://en.wikipedia.org/wiki/List_of_Firefox_OS_devices) running Firefox OS have been created and some boards (like [Raspberry Pi](http://www.raspberrypi.org/firefox-os-for-raspberry-pi/)) can run FFOS.

**Comment by aesedepece** [comment]
We started using the "phone" word because the Mozilla style guidelines encouraged so at the time (June 2013). 

I'm completely aware that Firefox OS is no longer a phone-only OS, and we'll see it arriving to plenty different devices and platforms in the following months and years. Nevertheless, we still haven't found any recent statement or recommendation from the UI/UX team on what term should be used instead of "phone".

I suppose you are suggesting to replace "phone" with something like "device". I personally support it, let's gather more user feedback and discuss it.

Thanks!

**Comment by bdcomp** [comment]
It looks like "device" used on the recent versions of Firefox OS.
Just take a look here (DNT screenshot):
http://www.xperiablog.net/2014/07/04/firefox-os-demoed-on-the-xperia-sp/

So, if it's agreed, I can take it.

**Comment by airon90** [comment]
I'm sorry. As I'm not a dev, I never read any doc from UI/UX team.
@aesedepece just consider my suggest, if the reccomendations changed
