### ISSUE TITLE
Emoji icons

### ISSUE THREAD

**Issue by Gioyik** [loqui/im#44]
Do you have plans or ideas to integrate emoji icons?

**Comment by Gioyik** [comment]
This module could help, but it's deferred:

http://xmpp.org/extensions/xep-0038.html

This is the one that uses piddgin:

http://xmpp.org/extensions/xep-0231.html

**Comment by aesedepece** [comment]
I'm currently working on #12 which is blocking for this, #11 and many others.

When done with that, this may be the next issue to solve and then maybe the huge #8.

**Comment by aesedepece** [comment]
A first emoji icons implementation has been done in 7129fe9f3cc45f227e8303885cdcaae3b6400287

**Comment by Gioyik** [comment]
I am seeing something. In `scripts/waalt/app.js`

``` javascript
var EmojiList = [
  ['>:-(', '>:('],
  [';)', ';-)'],
  [':-!', ':!'],
  [':-[', ':['],
  [':-$', ':$'],
  [':-\\'],
  [':\'('],
  [':-(', ':('],
  ['8-)', '8)'],
  [':-D', ':D'],
  ['>:O'],
  [':-O', ':O', '=-O'],
  ['O:-)'],
  [':-)', ':)'],
  [':-P', ':P'],
  [':-X'],
  [':kiss:', ':heart:'],
  [':yes:'],
  [':no:']
];
```

This is the list for emojis and when render it. Some of them are not working when you sent it in Facebook accounts. 

![captura de pantalla de 2013-10-28 00 09 33](https://f.cloud.github.com/assets/1834718/1417507/3c59f3d6-3f8f-11e3-9e2a-2ef1fd36873b.png)

![captura de pantalla de 2013-10-28 00 09 53](https://f.cloud.github.com/assets/1834718/1417510/43e977ca-3f8f-11e3-92fa-5b90d91a7315.png)

I like two know why there are two columns for emojis? and how this list works. I have some code to fix this problem but i like to be sure first before to make changes and send a pull.

**Comment by aesedepece** [comment]
The first column `EmojiList[i][0]` is the "preferred form" of the emoticon. That means the actual text that is in the body of the message when you send it.

The following columns are "alternative" representations. All off them are replaced by the same emoticon from the first column.

I tested all of them with XMPP and Pidgin, but Facebook could need some more alternative forms or different preferred forms.

Maybe we could make the emojilist depend on the account provider so that we have different emoticon sets for each one. (This will be necessary for future providers which send emoticons as unrecognisable bytes).

**Comment by Gioyik** [comment]
Do you have something planned for the v0.1.3 related to this issue? I ask because i am not sure why this is on the milestone.

By the way, I agree to have different emojilist depending on the account. Do you have an idea of how to show something depending on the account? Knowing this, i can work on a fast solution for this to close the issue.

**Comment by aesedepece** [comment]
> i am not sure why this is on the milestone.

Indeed, no changes on emoji icons are planned for this milestone...

I think we'd better close this issue and create new ones with specific problems or improvements to the emoji icons list when needed.
