### ISSUE TITLE
Opening the app takes me to the list of application files.

### ISSUE THREAD

**Issue by niktto** [loqui/im#49]
After installing 0.0.11 on my phone and opening it - application shows part of firefox-style error page with a list of .htm files and folders. I figured that I need to click index.htm to start, but I believe that startup process was designed differently ;).

I don't really know what I can attach to this issue - where can I find some log files that would help you fix this?

**Comment by aesedepece** [comment]
That has happened before to me not only with Loqui but with other apps.
As of Firefox OS 1.1, I believe that issue is not happening any more.

Best way to debug any FirefoxOS app is connecting your phone to your PC and running `adb logcat | grep GeckoConsole`. This should print out every javascript errors and warnings.
