### ISSUE TITLE
Persona support

### ISSUE THREAD

**Issue by nukeador** [loqui/im#5]
It would be nice to be able to log in using your Persona ID account, instead of having to create a new one or the server to deal with passwords.

http://identity.mozilla.com/post/47114516102/persona-on-firefox-os-phones

**Comment by aesedepece** [comment]
LOQUI is intended to be used with accounts from arbitrary Jabber providers, so by default we can't use any registering/logging in method other than those provided by XMPP standard.

Nevertheless, Persona would be an easy and safe method to "easy login" option which will be eventually used by most users who do not want to get into setting hosts or BOSH urls, as it will register a "nickname@loqui.im" account by only asking the user to enter a nickname and password.

On the other hand, Persona wouldn't free us from dealing with passwords, as "nickname@loqui.im" accounts should still be accessible from any other Jabber client using plain XMPP.

So, for people who have further experience with Persona: is there any feasible way to implement it so that it gets along with XMPP? Share your thoughts, please ;)

**Comment by Gioyik** [comment]
This could be work.

https://github.com/nikhilm/browserid-xmpp

**Comment by TitanNano** [comment]
persona is going to be discontinued
