### ISSUE TITLE
bosh gateway

### ISSUE THREAD

**Issue by markuman** [loqui/im#50]
what are you using as bosh gateway?
prosody as gateway failed if i change "bosh": "https://app.loqui.im/http-bind" in scripts/waalt/app.js to my gateway.

**Comment by aesedepece** [comment]
We are using Punjab [1] as the main BOSH gateway.
Anyway, we have previously tested that Prosody bundled BOSH gateway works as well.

[1]  https://github.com/twonds/punjab

**Comment by markuman** [comment]
do you have just enabled "bosh"; in prosody?
And do you have setup a proxy redirect with apache/nginx/lighttpd from https://app.loqui.im/http-bind to bosh port?

**Comment by aesedepece** [comment]
In addition to the "bosh" thing in the modules_enabled section in prosody.cfg.lua, when we used prosody's bundled gateway instead of punjab, we used to have some other settings at the end of the prosody config file:

```
bosh_ports = { 5280 }
consider_bosh_secure = true
bosh_max_inactivity = 300
cross_domain_bosh = true
```

We use Nginx for proxying connections by using this setup inside the proper virtual host:

```
location /http-bind {
  proxy_pass http://127.0.0.1:5280;
  proxy_method POST;
  proxy_buffering off;
  proxy_read_timeout 300;
  proxy_send_timeout 300;
  tcp_nodelay on;
  access_log /var/log/nginx/loqui/bind.access.log;
  error_log /var/log/nginx/loqui/bind.error.log;
}
```
