### ISSUE TITLE
Sliding sidebar

### ISSUE THREAD

**Issue by kkdeep** [loqui/im#51]
How you had created the sliding sidebar?

**Comment by aesedepece** [comment]
All the UI has been created using Lungo.js [1]
Please tell me if you need any help setting it up in your own projects.

[1] http://lungo.tapquo.com/

Regards!

**Comment by kkdeep** [comment]
Thanks! Yes i do need a bit of help. Mailed you on your id. :)

**Comment by kkdeep** [comment]
How can i open a link a  within the app?

I have set 

```
    <li data-event='firefoxsite'><a data-icon='refresh'>Firefox Website</a></li>
```

in the main.html & in binding.js i am using 

$$('aside#options li[data-event=firefoxsite]').on('click', function (e) 
{
 window.location = "https://www.mozilla.org/en-US/firefox/fx/"
});

On clicking the "Firefox Website" menu its opening in the browser. Is it possible to open the link within the  app itself?

**Comment by aesedepece** [comment]
In FirefoxOS, apps are loaded as "iframe mozbrowser" elements. So, as with any other kind of window or iframe, is subject of the browser same-origin policy [1].

Since your app may have been given some permissions over system elements or user data, it's considered unsafe to load any kind of resource from domains other than the one in your app manifest and thus redirects are made in a separate zero-permission browser window.

[1]  http://en.wikipedia.org/wiki/Same_origin_policy
