### ISSUE TITLE
[WhatsApp] status not available

### ISSUE THREAD

**Issue by ghost** [loqui/im#564]
I noticed, that you cannot view the status of your contacts until you have sent them a message and restarted the app. For all contacts that you haven't send a message to since you are using Loqui, the status will be "status not available".

Whatsapp - ZTE Open C FFOS 1.3

**Comment by gargsms** [comment]
It is because the status and pictures for contacts that you have not had any chats with are lazily loaded.
Supposing someone has over 200 contacts, and has been chatting with only a few 40, it is just a wastage of bandwidth to load all the other data which is not needed.

I have noticed similar issues. Sometimes it will fetch the status and picture right away, sometimes you need to exchange few chats before the status is loaded.
