### ISSUE TITLE
[Facebook] Synchronize messages

### ISSUE THREAD

**Issue by airon90** [loqui/im#652]
Hi, 
I just reinstalled Loqui after reinstalling Firefox OS and I set up my Facebook account.
I don't know if it is a bug, a feature request or is an intended behaviour but I found out that Loqui doesn't synchronize with Facebook to get old messages.

**Comment by gargsms** [comment]
Well, none of the apps I know of do so.
@TitanNano any ideas?

**Comment by TitanNano** [comment]
This is not supported. 
I thinks it lays in the nature of XMPP? As far as I know XMPP does not intend to send old messages, since XMPP servers do not save messages. So it's not possible to retrive old messages from Facebook when we connect via XMPP. You also miss messages from Facebook if you're not online.

**Comment by aesedepece** [comment]
- XMPP does support message archiving with XEP-0136 http://xmpp.org/extensions/xep-0136.html
- Facebook doesn't because the only XEPs supported are XEP-0054 (vCard) and XEP-0085 (CSN)
- Facebook never provided any method or API for message history retrieval.
- More info about FB Chat API, to be deprecated on April 30: https://developers.facebook.com/docs/chat/

(Yes, on April 30 Loqui IM will stop supporting Facebook Chat, sorry) :disappointed:

**Comment by airon90** [comment]
> (Yes, on April 30 Loqui IM will stop supporting Facebook Chat, sorry) :disappointed: 

Why?

**Comment by aesedepece** [comment]
Facebook will drop XMPP support in that very date and every unofficial Facebook Chat app will die. :crying_cat_face:

**Comment by airon90** [comment]
I didn't know that! Thank you very much!

**Comment by ghost** [comment]
@aesedepece should the Loqui IM users be informed about that soon missing feature, somehow?
