### ISSUE TITLE
what does color codes mean?

### ISSUE THREAD

**Issue by pravi** [loqui/im#665]
I think settings-> info should mention these. What does red box around text means? I think it means ack recieved, but not sure.

**Comment by TitanNano** [comment]
what exactly do you mean with "red box around text"?

**Comment by pravi** [comment]
![2015-03-26-21-05-02](https://cloud.githubusercontent.com/assets/708222/6850055/bf12e2d0-d3fc-11e4-8fb9-51381a46aa90.png)

in attachment you can see green tick marks before some messages I sent and red box and grey background for some other text. Sometimes I see yellow background.

**Comment by gargsms** [comment]
That means the message did not get pushed to the server.

**Comment by TitanNano** [comment]
yellow background => message has been sent but no acknowledgment from the server yet.
gray message with border => we either couldn't send the message to the server or we didn't get any acknowledgment in the set time frame (I thinks it's 30 seconds). So that means the server didn't receive our message.

**Comment by pravi** [comment]
In that conversation 'Hey' is red background, green tick mark and 'Great' is grey background and red nic around. What does both indicate?

**Comment by TitanNano** [comment]
red background means the message is okay (properly sent). The tick means we only know that the server received your message. Two ticks mean we also know that you're partner received the message on his device. (not every provider supports that)

**Comment by pravi** [comment]
This need to be documented and users should be able to see the explanation easily. I get replies even when there is red border around gray background.

**Comment by TitanNano** [comment]
which provider do you use?

**Comment by TitanNano** [comment]
I experience this also sometimes. The problem is, when we don't receive the acknowledgment from the server for what reason ever (weak / wonky connection) we can't tell if the message really arrived at the server.

**Comment by TitanNano** [comment]
I guess we need some kind of FAQ like whatsapp and other providers have one :/

**Comment by pravi** [comment]
i use autistici.org 

we definitely need to collect xeps required for proper mobile operation and call it 'xmpp mobile' and create mobile.xmpp.net with checkmark against these for apps and services. i think mobile app developrs should take initiative on this. can loqui team propose this?

**Comment by pravi** [comment]
Also timeout should be adjusted with connection speed dynamically.

**Comment by gargsms** [comment]
I believe the issue is not with the duration of the timeout. A message may get sent properly but then the connection is lost causing the ACK to never arrive. In this case, no matter how long the timeout be, there is no use of listening for the ACK. The packet is lost completely.

Also, determining the connection speed is a tricky business. There are no reliant methods, except for keeping an average estimated speed for each connection type (EDGE, HSPA, HSDPA, LTE, Wi-Fi etc.)
Sounds strange to do.

The XEP proposal will surely facilitate development. :+1:

**Comment by TitanNano** [comment]
@gargsms right :+1:

**Comment by pravi** [comment]
That is why we need #659 desperately.

**Comment by TitanNano** [comment]
I still don't quite understand how this new encryption protocol and wonky connections are related. Could you explain that?

**Comment by pravi** [comment]
This new protocol does not assume a continuous connection. So it will have additional checks for reliable delivery. It is designed for a mobile environment with frequent connection loses.

**Comment by gargsms** [comment]
https://github.com/loqui/im/wiki/FAQ#conversation-colour-codes

Fixed.
