### ISSUE TITLE
can ideas from mosh project be used to keep live sessions for xmpp?

### ISSUE THREAD

**Issue by pravi** [loqui/im#690]
As a remote shell it works beautfully http://mosh.mit.edu/ even when the connection drops for long time. Can same ideas be reused to keep sessions alive?

From their faq,

Q: Are the mosh principles relevant to other network applications?

```
We think so. The design principles that Mosh stands for are conservative: warning the user if the state being displayed is out of date, serializing and checkpointing all transactions so that if there are no warnings, the user knows every prior transaction has succeeded, and handling expected events (like roaming from one WiFi network to another) gracefully.

Those don't seem too controversial, but fancy apps like Gmail-in-Chromium or on Android still behave atrociously on dodgy connections or after switching IP addresses. (Have you ever had Gmail leave an e-mail message in "Sending..." for ten hours while merrily retrieving new mail and not indicating any kind of error? Us too.) We think there may be considerable room for improvement in many network user interfaces from the application of these values.
```

**Comment by gargsms** [comment]
While mosh is a great thing, I cannot derive any analogy between XMPP and Mosh.If by keeping sessions alive you meant maintaining online status, then I think it contradicts the whole IM principle. You need to be at the receiving end to be online.XMPP and Shell are quite different IMO. In shell, there are sessions and states. A single user can be logged into multiple sessions at the same time, accessing resources independently. In XMPP, there are sessionless clients. If the client is present with valid credentials and is able to ping the server, the server will push the necessary packets.In shell, the server needs to keep track of the clients sessions and control usage. In XMPP, AFAIK, the client needs to 'ask' the server to push messages.
As for roaming while using XMPP, Loqui does connect as soon as there is any network connectivity. I have been using XMPP on it and I did switch between totally independent networks, Wi-Fi from LAN and 2G from the provider. My messages were delivered just fine and I received the pooled messages at the server too.
Packet loss is always a problem with intermittent connections. Mosh deals with it because it maintains a state at the server side. XMPP servers, on the other hand, do not keep a copy of the messages. And there is no state. The messages are pushed as soon as the client is available to receive them. It may happen in the process that the packet is lost. This cannot be handled then.

I may be wrong, however, at understanding your approach.

**Comment by pravi** [comment]
I feel these ideas can be used for better offline messages. I thought it would be useful to share it here. mosh can easily keep me online even when the connection breaks for a long time, but loqui can't keep me online once connection drops, it does not reconnect automatically. I thought we may need to rethink on our approach to this problem, I found mosh has an innovative approach.
