### ISSUE TITLE
Facebook XMPP Chat API dropped – should Facebook support be remove?

### ISSUE THREAD

**Issue by ghost** [loqui/im#700]
Facebook dropped the support for their XMPP Chat API after April 30th, 2015

https://developers.facebook.com/docs/chat

What does that mean for the Facebook support of Loqui IM?

**Comment by gargsms** [comment]
I guess we need to be done with it.Also, in the new API, there isn't any endpoint to access chat. I believe chat.facebook.com is dead now.

**Comment by ghost** [comment]
Should the Facebook support be removed from the Loqui IM website (Home, F.A.Q., About, ..) and from the Firefox Marketplace description first? And than from the Loqui code?

Should there be an announcement for that? Blog, Twitter, Changelog, ..

**Comment by TitanNano** [comment]
yes, we should remove it in the next release. If you like you can do that :) at least here in the repo wiki and code.

**Comment by TitanNano** [comment]
@aesedepece the website needs an update 😉

@bobcanthelpyou I'll remove the Facebook bits from the source soon.

**Comment by TitanNano** [comment]
@aesedepece when I remove the facebook support I'll implement a little info pop up telling the users that facebook isn't supported anymore. Should we delete the Facebook accounts from the device?

**Comment by ghost** [comment]
Maybe it is still possible to login to Facebook (but it doesn't work at all, i am stuck at the sign-in screen), but an session (from the bosh server) is opened successfully and i also see my Facebook contact names in the WebIDE logs.
![bildschirmfoto vom 2015-05-10 09 21 24](https://cloud.githubusercontent.com/assets/4523264/7553392/ae801c22-f6f6-11e4-9899-d490c3647804.png)

**Comment by ghost** [comment]
Not sure why, but facebook still works for me. Both on Loqui (Phone) & Pidgin (on my desktop PC)

**Comment by gargsms** [comment]
As per the facebook documentation, these APIs will be removed anytime after April 30. That means some of them will remain functional for not sure how long. It has been just 11 days past the deadline. But yes, they will be removed soon.

**Comment by TitanNano** [comment]
I think we should remove Faceook support and not wait until it stops
working. Users will be confused if it just stops working.

2015-05-11 8:50 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by caos30** [comment]
Hey guys, i'm a new user of Firefox OS (2.1 in a LG FX0... one of these that are now in Amazon by $50 USD !). So, as you can understand, the first thing i did was to install Loqui for access Whatsapp (mainly). But i've lost at least 2 hours making attempts to login on Facebook Messenger chat with Loqui, and searching at internet about it. Finally i've found this thread :(

So, my suggestion is to quit asap the option to connect to Facebook account from Loqui app!!! 

Said this, i'm a senior web developer (LAMP) and i would like to begin to work developing Firefox OS apps. So, because the best way to learn is collaborating with existing projects, i would like to collaborate with this project.

Please, can someone help me to begin to work with you? i readed your instructions in https://loqui.im but i would feel more comfortable having a first contact by chat with someone of the team, maybe for put me clear some warnings, priorities, etc...

So, sincerely i'm open and waiting for your contact (on faceboook? sergi.rodriguesrius). 

Thanks in advance! Indeed, i'm from Barcelona, but i'm living on Sonora (Mexico). I say this for speak in spanish better if you too.

Cheers.

**Comment by TitanNano** [comment]
you can just start working on a bug. If you want we will assign you to it so others won't work at it the same time. I don't think we have any priorities right now so just choose one, for example this one. If you have questions just post them into the issue. Most of the contributors don't speak Spanish so we appreciate when public conversations are held in english.

**Comment by caos30** [comment]
Ok, thanks Jovan for your answer. Understood about the planning work of the
project. No problem with english. I suppose i can ask you doubts about
project, but are there any "chat" or "forum" only for developers, where i
can query to the rest of the team about doubts, etc...

Thanks,
Sergi

**Comment by TitanNano** [comment]
no, right now there is no chat or mailing list. Usually we just communicate though tickets.

**Comment by aesedepece** [comment]
There is used to be a mailing at http://lists.waalt.com/cgi-bin/mailman/listinfo/loqui.core :wink:

**Comment by ghost** [comment]
It seems that the Facebook support was remove. Closing the issue.
