### ISSUE TITLE
Let's add jsdoc documentation to our codebase

### ISSUE THREAD

**Issue by TitanNano** [loqui/im#861]
I'd like to add jsdoc to our source. With that we'd be able to generate a full documentation for new contributors. In a first step I created a documented version of chat.js
https://gist.github.com/TitanNano/c47e6922b7bcb8f8510a

Please tell me if there are any objections. Otherwise i will land app.js and chat.js tomorrow.

**Comment by gargsms** [comment]
I believe we should also indent the JS files properly. For now, it is really hard to find something in the code without spending considerable time. That applies for new contributors, of course.

**Comment by TitanNano** [comment]
Yes if you look at the Gist, I changed the indent to 4 spaces. I think that's better.

**Comment by gargsms** [comment]
Adding JSDoc is great. :+1: 
I think 2 spaces is more of a convention in the JS community.
But let's have an opinion on it.

@cmeerw @aesedepece What do you say?

**Comment by TitanNano** [comment]
@gargsms actually 4 spaces is more of a convention for JS.
http://www.w3schools.com/js/js_conventions.asp pretty far down - searching for "Code Indentation" helps
https://google.github.io/styleguide/javascriptguide.xml#Code_formatting 
http://javascript.crockford.com/code.html

But we just need to agree on one. I personally prefer 4 because it's more readable, but I'm open for other suggestions.

**Comment by gargsms** [comment]
Ah. Well, it depends on the project. We can decide any we want, and then stick to it.Mozilla Gaia has 2 spaces as far as I know.I have stalked ThreeJS enough, and they have an insane 8 character `tab`.I personally prefer spaces over tabs. The amount of spaces is not much of a big deal.

```
 On Sunday, 1 November 2015 12:35 AM, Jovan Gerodetti <notifications@github.com> wrote:
```

 @gargsms actually 4 spaces is more of a convention for JS.
http://www.w3schools.com/js/js_conventions.asp pretty far down - searching for Code Indentation helps
https://google.github.io/styleguide/javascriptguide.xml#Code_formatting 
http://javascript.crockford.com/code.htmlBut we just need to agree on one. I personally prefer 4 because it's more readable, but I'm open for other suggestions.—

**Comment by TitanNano** [comment]
yes Gaia uses 2 spaces. 
I agree, spaces are better than tabs. For the amount, let's just stick with the 2 spaces we are using already.
