### ISSUE TITLE
Google hangout not connect

### ISSUE THREAD

**Issue by neuberoliveira** [loqui/im#89]
I was trying to add my google account, but i get a message saying "Authentication Failed Login or password invalid"

I triple checked the login and user and both are correct.
2 Steps authentication are disable in my account.

Google alert me about a suspicious login attempt, so i recognized the activity

Even so i unable to connect to google.

**Comment by Gioyik** [comment]
Are you continue feeling this problem? Could you test with the latest version in the Marketplace or downloading the code from the repo?

**Comment by vitalyster** [comment]
Not able to log in with my Google account, it stuck on "Connecting".

**Comment by Gioyik** [comment]
@vitalyster Could you provide us a log or something that shows us what is happening?

**Comment by vitalyster** [comment]
@Gioyik where to get something useful? I see "console" in App Manager with "POST https://app.loqui.im/http-bind/" lines, but there is nothing interesting yet.

**Comment by vitalyster** [comment]
It is detected as "Suspicious activity" by Google, trying to unblock now. As I understand, you are using deprecated clientLogin/X-GOOGLE-TOKEN authentication, it would be better switching to OAuth authentication.

**Comment by aesedepece** [comment]
@vitalyster I agree. We'd better implement OAuth for Google and Facebook accounts. Plain authentication is a pain for some users.

**Comment by Gioyik** [comment]
Shit! Yesterday i saw a xmpp client using strophe that works with OAuth for Facebook connection. I need to review a universally infinite history, probably i have a fast solution that is a pain for many users. ;)

**Comment by Gioyik** [comment]
Ok i got it! I have the libraries to implement OAuth authentication. I will test and workaround.

**Comment by nexus42** [comment]
Any progress on this? I cannot connect still. I use ZTE Open with FFOS v1.1

**Comment by autra** [comment]
Might be related : I wonder why loqui IM does authentication from a server in Germany (??) to log into my google account. I trust loqui IM, but isn't it possible to use my direct internet connection to do it? 

I don't like a server I don't trust to connect to my accounts... Is it related to this bug, or should I open a new one?

**Comment by aesedepece** [comment]
@autra Even nowadays that we have the TCPsockets API, the most reliable way of using XMPP in a mobile device is using a technique called [BOSH](http://en.wikipedia.org/wiki/BOSH). This implies that your connection is tunnelled through a high-grade [TLS](http://en.wikipedia.org/wiki/Transport_Layer_Security)-secured gateway hosted at https://bosh.loqui.im. This also hides your actual IP from your provider so that they can't track you.

For the sake of [perfect forward secrecy](http://en.wikipedia.org/wiki/Forward_secrecy), the upcoming 0.3.0 version will allow you to cypher your chats end-to-end by using the [Off-the-Record](http://en.wikipedia.org/wiki/Off-the-Record_Messaging) messaging protocol, which is available in other XMPP clients for PC ([Pidgin](http://pidgin.im/)) and Android ([Xabber](http://www.xabber.org/)).

**Comment by Gioyik** [comment]
The solution is planned with this fix for #122. Discuss there. :)
