### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by buluma** [loqui/im#943]
I've had an issue with Loqui creating thousands of log files and therefore filling up the memory and causing issues with the phone. Two times I've been unable to reboot the phone normally. After digging around, I realized this was the problem and deactivated logs from the developer menu.

Two questions,
- Why so many log files in a span of 12 hours? and
- What are the effects of disabling logs files?

**Comment by TitanNano** [comment]
1. we create a new log file every time the current log file reaches a size of 1 MB since we always need to load the entire log file into memory if we want to append something.
2. the effect of disabling logs is, you won't have logs. If you don't have any issues with Loqui disable the log files. Log files should be disabled by default.

**Comment by buluma** [comment]
Thanks @TitanNano I actually went with the option of disabling the logs. I realized at some point I was digging around and left logs enabled and that's what was troubling my device. 

All is working correctly now.
