### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by tibtab** [loqui/im#971]
In the newest build one line break appears as two line breaks. 
Btw when you input an emojee there is always a line break in front of it. Is that necessary?

**Comment by cmeerw** [comment]
Ok, I need to look at that again a bit further... I did change the
handling because the previous caused other problems like escaping <, >
and & twice.

**Comment by cmeerw** [comment]
Looks like the 2 line breaks was just a rendering issue (and I am not
sure that I broke it). Anyway, please retest now.

I am only seeing the line break in front of an emoji for XMPP
accounts, but not for WhatsApp - and it looks like that's just when
inserting the emoji and can be deleted again. Not sure when I will get
time to look at this further... I'd kind of like to push the current
version to the marketplace sooner rather than later unless there is
any showstopper issue...
